words = ['apple' , 'banana', 'cherry', 'date']
print (words[1].upper())
print (words[0].title() + " " + words[2].title())
print ("I like to eat " + words[3] + "s every day.")
words[1] = 'berries'
print (words)
words.append('eat')
print ("I like to " + words[-1] + " " + words[1].upper() +".")

pets = []
pets.append('dog')
pets.append('cat')
pets.append('hamster')
pets.append('fish')
print (pets)

pets.insert(2, 'rabbit')
pets.insert(4, 'guinnea pig')
print (pets)

pets.pop(-1)
print (pets)
past_pet = pets.pop(-2)
print ("I used to have a " + past_pet.title() + ".")
sister_pet = pets.pop(1)
print ("My sister has 2 " + sister_pet +"s.")
print (pets)
del pets[2]
print (pets)
print (pets[1].upper())
pet = 'dog'
print (pet.upper())
pets.remove('rabbit')
print (pets)

#to sort alphabetically & PERMANENTLY, use 'list'.sort()
cars = ['bmw', 'audi', 'toyota', 'subaru']
cars.sort()
print (cars)
cars.sort(reverse=True)
print (cars)

#to sort TEMPORARILY, use sorted('list')
cars_orig = ['bmw', 'audi', 'toyota', 'subaru']
print ("\nHere's the original list:")
print (cars_orig)
print ("\nHere's the sorted list:")
print (sorted (cars_orig))
print ("\nHere's the original list again:")
print (cars_orig)
print (sorted(cars_orig, reverse=True))

print (cars_orig)
cars_orig.reverse()
print (cars_orig)
cars_orig.reverse()
print (cars_orig)

len(cars_orig)
print (len(cars_orig))

#practice chapter 3
hailey_friends = ['Timmy', 'Maddie', 'Charlotte', 'Eli', 'Addie', 'Willow', 'Ayden']
print (len(hailey_friends))
print ("\nHailey has " + str(len(hailey_friends)) + " friends she likes to play with at school.") 
print ("\n")
print (hailey_friends)
print ("\nIf you put them in alphabetical order, you'll get this list:")
print (sorted(hailey_friends))
print ("\n")
print ("Add one more friend:")
hailey_friends.append('Gigi')
print (hailey_friends)
print ("\nAnd one more:")
hailey_friends.insert(0,'Reagan')
print (hailey_friends)
print ("\n")
best_friend = hailey_friends.pop(2)
print ("\nHailey's best friend is " + best_friend + " .")
print ("\n")
print (len(hailey_friends))
print ("\n")
print ("\n")
print(sorted(hailey_friends,reverse=True))
hailey_friends.reverse()
print ("\n")
print (hailey_friends)
hailey_friends.remove('Reagan')
print ("\n")
print (hailey_friends)
del hailey_friends[3]
print ("\n")
print (hailey_friends)
hailey_friends[-1] = 'Emma'
print ("\n")
print (hailey_friends)
print ("\n")
hailey_friends.sort()
print (hailey_friends)
print ("\n")
print ("Hailey also loves to play with " + hailey_friends[-1] + ".")
print (hailey_friends[-1].upper())
print("\n")
hailey_friends.sort()
print (hailey_friends)
help (print)
